/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTroubleshootRouteImport } from './routes/api/troubleshoot'
import { Route as V1TroubleshootRouteImport } from './routes/v1/troubleshoot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTroubleshootRoute = ApiTroubleshootRouteImport.update({
  id: '/api/troubleshoot',
  path: '/api/troubleshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TroubleshootRoute = V1TroubleshootRouteImport.update({
  id: '/v1/troubleshoot',
  path: '/v1/troubleshoot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/troubleshoot': typeof ApiTroubleshootRoute
  '/v1/troubleshoot': typeof V1TroubleshootRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/troubleshoot': typeof ApiTroubleshootRoute
  '/v1/troubleshoot': typeof V1TroubleshootRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/troubleshoot': typeof ApiTroubleshootRoute
  '/v1/troubleshoot': typeof V1TroubleshootRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/health' | '/api/troubleshoot' | '/v1/troubleshoot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health' | '/api/troubleshoot' | '/v1/troubleshoot'
  id:
    '__root__' | '/' | '/api/health' | '/api/troubleshoot' | '/v1/troubleshoot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTroubleshootRoute: typeof ApiTroubleshootRoute
  V1TroubleshootRoute: typeof V1TroubleshootRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/troubleshoot': {
      id: '/api/troubleshoot'
      path: '/api/troubleshoot'
      fullPath: '/api/troubleshoot'
      preLoaderRoute: typeof ApiTroubleshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/troubleshoot': {
      id: '/v1/troubleshoot'
      path: '/v1/troubleshoot'
      fullPath: '/v1/troubleshoot'
      preLoaderRoute: typeof V1TroubleshootRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTroubleshootRoute: ApiTroubleshootRoute,
  V1TroubleshootRoute: V1TroubleshootRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
